### ISSUE TITLE
Errors on PyV8 binary loading

### ISSUE THREAD

**Issue by ntzm** [emmetio/emmet#316]
Hi, I am moving from Windows to elementary OS, and when I try to install emmet, I get the error below in the console. I have tried 32 bit and 64 PyV8 packages in Python 2 and 3, but I always get the same error. I have also tried reverting, which did nothing.

```
Emmet: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
Emmet: Loading PyV8 binary from https://raw.github.com/emmetio/pyv8-binaries/master/pyv8-linux64-p3.zip
Exception in thread Thread-220:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "X/threading.py", line 825, in run
  File "/home/nat/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet/pyv8loader.py", line 271, in run
    return self.trigger('error', exit_code=self.thread.exit_code, progress=self)
  File "/home/nat/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet/pyv8loader.py", line 290, in trigger
    c(*args, **kwargs)
TypeError: on_error() got an unexpected keyword argument 'progress'
```
##

**Comment by wookiecooking** [comment]
Same issue on Xubuntu 14.04

**Comment by bayronq** [comment]
solution:
https://www.youtube.com/watch?v=k3Ezso475dY

**Comment by sergeche** [comment]
Upcoming Emmet version won’t use PyV8 anymore
