### ISSUE TITLE
Doesn't work on CentOS 6.6

### ISSUE THREAD

**Issue by yusk90** [emmetio/emmet#387]
On Tab press nothing happens. On Ctrl+E alert message says "Please wait a bit while PyV8 binary is being downloaded". Tried to install PyV8 binaries automatically through Package Control and manually - doesn't work. 
CentOS 6.6
gcc 4.4.7
glibc-2.12-1.149
Any suggestions? Thank you in advance.

>>> sublime.log_commands(True)
command: drag_select {"event": {"button": 1, "x": 82.5, "y": 42.5}}
command: left_delete
command: insert_best_completion {"default": " ", "exact": false}
command: left_delete
command: run_emmet_action {"action": "expand_abbreviation"}
command: expand_as_you_type
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "emmet-plugin in /home/prog5/.config/sublime-text-3/Installed Packages/Emmet.sublime-package", line 580, in run
  File "emmet-plugin in /home/prog5/.config/sublime-text-3/Installed Packages/Emmet.sublime-package", line 682, in setup
AttributeError: __exit__

**Comment by toanqc** [comment]
same issue with RedHat 6.7, this can't be fixed? see this open for long.... but doesn't have any progress
