### ISSUE TITLE
Emmet not expanding abbreviation on OSX+Sublime3

### ISSUE THREAD

**Issue by renatogalvones** [emmetio/emmet#432]
OS: Yosemite(10.10.5)
Sublime: 3103
PyV8 Bynaries: installed manually(pyv8-osx-p3)

I'm trying basic usage like:
```
.class{
    h10
}
```

I've already tried reinstalling Emmet package but it's still not working.

The moment I hit tab key, this error is printed on the console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 354, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "emmet-plugin in /Users/renatogalvao/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package", line 493, in on_query_context
  File "emmet-plugin in /Users/renatogalvao/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package", line 187, in check_context
  File "/Users/renatogalvao/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 200, in js
    self._use_unicode = should_use_unicode()
  File "/Users/renatogalvao/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 57, in should_use_unicode
    ctx = PyV8.JSContext()
AttributeError: 'module' object has no attribute 'JSContext'
command: insert_best_completion {"default": "	", "exact": false}
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 377, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "emmet-plugin in /Users/renatogalvao/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package", line 497, in on_query_completions
  File "emmet-plugin in /Users/renatogalvao/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package", line 187, in check_context
  File "/Users/renatogalvao/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 200, in js
    self._use_unicode = should_use_unicode()
  File "/Users/renatogalvao/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 57, in should_use_unicode
    ctx = PyV8.JSContext()
AttributeError: 'module' object has no attribute 'JSContext'
```

**Comment by itsmehran** [comment]
I have exactly the same problem on Ubuntu 14.04.4
It took 5 hours of my time and still console just will show these errors!
On Brackets it just take 5 seconds to install emmet :|

**Comment by sergeche** [comment]
Please post a full console log when after you start Sublime Text

**Comment by itsmehran** [comment]
`DPI scale: 0.875
startup, version: 3103 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/mehran/.config/sublime-text-3/Packages
state path: /home/mehran/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/mehran/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
Unable to decode Packages/Material Theme - Appbar/assets/commons/dirty_icon.png
pre session restore time: 2.63069
startup time: 2.91859
first paint time: 2.92339
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Blade Spacer.BladeSpacer
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin PHP Companion.PHP Companion
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PhpDoc.CodeDoc
reloading plugin SublimeLinter-csslint.linter
SublimeLinter: csslint linter loaded 
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin SublimeLinter-json.linter
SublimeLinter: json linter loaded 
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin PlainTasks.PlainTasks
reloading plugin PyV8.PyV8
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/mehran/.config/sublime-text-3/Packages/PyV8/PyV8.py", line 32, in <module>
    import _PyV8
ImportError: No module named '_PyV8'
reloading plugin SublimeAllAutocomplete.all_views_completions
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
Traceback (most recent call last):
  File "emmet-plugin in /home/mehran/.config/sublime-text-3/Installed Packages/Emmet.sublime-package", line 101, in init
  File "emmet-plugin in /home/mehran/.config/sublime-text-3/Installed Packages/Emmet.sublime-package", line 248, in update_settings
  File "/home/mehran/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 200, in js
  File "/home/mehran/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 57, in should_use_unicode
AttributeError: 'module' object has no attribute 'JSContext'
Package Control: Skipping automatic upgrade, last run at 2016-04-10 18:18:14, next run at 2016-04-10 19:18:14 or after`

**Comment by itsmehran** [comment]
DPI scale: 0.875
startup, version: 3103 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/mehran/.config/sublime-text-3/Packages
state path: /home/mehran/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/mehran/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
Unable to decode Packages/Material Theme - Appbar/assets/commons/dirty_icon.png
pre session restore time: 2.63069
startup time: 2.91859
first paint time: 2.92339
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Blade Spacer.BladeSpacer
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin PHP Companion.PHP Companion
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PhpDoc.CodeDoc
reloading plugin SublimeLinter-csslint.linter
SublimeLinter: csslint linter loaded 
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin SublimeLinter-json.linter
SublimeLinter: json linter loaded 
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin PlainTasks.PlainTasks
reloading plugin PyV8.PyV8
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/mehran/.config/sublime-text-3/Packages/PyV8/PyV8.py", line 32, in <module>
    import _PyV8
ImportError: No module named '_PyV8'
reloading plugin SublimeAllAutocomplete.all_views_completions
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
Traceback (most recent call last):
  File "emmet-plugin in /home/mehran/.config/sublime-text-3/Installed Packages/Emmet.sublime-package", line 101, in init
  File "emmet-plugin in /home/mehran/.config/sublime-text-3/Installed Packages/Emmet.sublime-package", line 248, in update_settings
  File "/home/mehran/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 200, in js
  File "/home/mehran/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 57, in should_use_unicode
AttributeError: 'module' object has no attribute 'JSContext'
Package Control: Skipping automatic upgrade, last run at 2016-04-10 18:18:14, next run at 2016-04-10 19:18:14 or after

**Comment by sergeche** [comment]
It’s unable to properly load PyV8 from `/home/mehran/.config/sublime-text-3/Packages/PyV8/`
Check out contents of this folder and try to re-install PyV8 manually: https://github.com/emmetio/pyv8-binaries#readme

**Comment by itsmehran** [comment]
@sergeche Many thanks.
Actually i have tried to do that  many times and still it is not working :/

**Comment by sergeche** [comment]
Can you post a screenshot of your PyV8 folder contents?

**Comment by itsmehran** [comment]
Ok!
![screenshot from 2016-04-10 18 40 21](https://cloud.githubusercontent.com/assets/7046255/14410759/c20f9868-ff4b-11e5-94df-c95cf6647e83.png)

**Comment by sergeche** [comment]
Try to rename `_PyV8.cpython-33m.so` to `_PyV8.so` and restart Sublime Text

**Comment by itsmehran** [comment]
Still same error .... :/

**Comment by sergeche** [comment]
Well, don’t know what the problem is. Need time to investigate it

**Comment by itsmehran** [comment]
Still same error .... :/

Maybe i should install some packages for my Ubuntu OS ??

**Comment by itsmehran** [comment]
We Hope you fix this error... :)
Good job and Many thanks again.

**Comment by renatogalvones** [comment]
Finally solved it!

The folder with the right name is the key to stop this annoying error.

![screen shot 2016-04-11 at 10 18 14 am](https://cloud.githubusercontent.com/assets/302819/14428248/b36a11de-ffce-11e5-99c8-002f0ed532ae.png)

**Comment by itsmehran** [comment]
The instructions of PyV8-binaries  says that:
`
Unpack contents of downloaded archive into PyV8/%filename% folder inside Sublime Text Packages (find Browse Packages... menu item in ST2 editor to get into Packages folder),
`

The cause of my problem was that i extracted PyV8 Folder to  Sublime Text Packages Folder!
But when i moved PyV8 to "Installed Packages" Folder, Emmet just worked like a charm !!
