### ISSUE TITLE
Clarification on callback in file.createPath

### ISSUE THREAD

**Issue by mrmlnc** [emmetio/emmet#454]
We have a function with callback:

```js
createPath: function(parent, fileName, callback) {
    var stat = fs.statSync(parent);
    if (stat && !stat.isDirectory()) {
      parent = path.dirname(parent);
    }
			
    return callback(path.resolve(parent, fileName));
}
```

But in Base64 this function is called without a callback:

```js
var absPath = file.createPath(editor.getFilePath(), filePath);
if (!absPath) {
  throw "Can't save file";
}
file.save(absPath, base64.decode( data.replace(/^data\:.+?;.+?,/, '') ));
```

And bang:

```js
callback is not a function: TypeError: callback is not a function
    at Function.utils.extend.createPath (\node_modules\emmet\lib\plugin\file.js:186:11)
    at decodeFromBase64 (\node_modules\emmet\lib\action\base64.js:84:22)
    at Object.encodeDecodeDataUrlAction (\node_modules\emmet\lib\action\base64.js:129:13)
    at Object.run (\node_modules\emmet\lib\action\main.js:150:21)
    at Object.run (\node_modules\emmet\lib\emmet.js:81:23)
```

**Comment by mrmlnc** [comment]
Closed by #456 #455
